steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "kms",
        "decrypt",
        "--ciphertext-file",
        "config/$BRANCH_NAME.env.enc",
        "--plaintext-file",
        "config/.env",
        "--location",
        "global",
        "--keyring",
        "demo-keyring",
        "--key",
        "demo-key",
      ]
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$BRANCH_NAME-$REPO_NAME", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$BRANCH_NAME-$REPO_NAME"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "$BRANCH_NAME-$REPO_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$BRANCH_NAME-$REPO_NAME",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
images:
  - gcr.io/$PROJECT_ID/$BRANCH_NAME-$REPO_NAME
